# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       qotpnitro

# >> macros
# << macros

%{!?qtc_qmake:%define qtc_qmake %qmake}
%{!?qtc_qmake5:%define qtc_qmake5 %qmake5}
%{!?qtc_make:%define qtc_make make}
%{?qtc_builddir:%define _builddir %qtc_builddir}
Summary:    A secure One Time Pad implementation GUI.
Version:    0.5.2
Release:    1
Group:      Qt/Qt
License:    LICENSE
URL:        http://www.haibane.org
Source0:    %{name}-%{version}.tar.bz2
Requires:   sailfishsilica-qt5 >= 0.10.9
BuildRequires:  pkgconfig(sailfishapp) >= 1.0.2
BuildRequires:  pkgconfig(Qt5Core)

%description
Short description of my SailfishOS Application


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%qtc_qmake5 

%qtc_make %{?_smp_mflags}

# >> build post
# << build post

%install
#rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake5_install

# >> install post
# << install post

mkdir -p %{buildroot}/%{_bindir}
mkdir -p %{buildroot}/%{_libdir}
mkdir -p %{buildroot}/%{_datadir}/applications/
mkdir -p %{buildroot}/%{_datadir}/qotpnitro/

cp %{name} %{buildroot}/%{_bindir}
cp ../libotpnitro.so %{buildroot}/%{_libdir}
ln -s %{_libdir}/libotpnitro.so %{buildroot}/%{_libdir}/libotpnitro.so.1

cp ../packages/debian/qotpnitro/usr/share/applications/OTPNitro.desktop %{buildroot}/%{_datadir}/applications/
cp ../packages/debian/qotpnitro/usr/share/qotpnitro/main_icon_64.png %{buildroot}/%{_datadir}/qotpnitro/

%files
%defattr(-,root,root,-)
%{_bindir}
%{_libdir}
%{_datadir}/applications/OTPNitro.desktop
%{_datadir}/qotpnitro/main_icon_64.png

# >> files
# << files
